
-- Enable the pgcrypto extension for hashing
create extension if not exists "pgcrypto" with schema "extensions";

-- API Keys Table
create table if not exists public.api_keys (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles on delete cascade not null,
    key_name text not null,
    api_key_hash text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    last_used_at timestamp with time zone,
    request_count bigint default 0
);

-- Indexes for performance
create index if not exists idx_api_keys_user_id on public.api_keys(user_id);
create index if not exists idx_api_keys_api_key_hash on public.api_keys(api_key_hash);

-- Enable Row Level Security
alter table public.api_keys enable row level security;

-- RLS Policies
drop policy if exists "Allow users to manage their own API keys" on public.api_keys;
create policy "Allow users to manage their own API keys" on public.api_keys
    for all
    using (auth.uid() = user_id);

-- Function to create a new API key
create or replace function public.create_api_key(p_user_id uuid, p_key_name text)
returns text as $$
declare
  new_key text;
  hashed_key text;
begin
  -- Generate a secure random string for the API key
  new_key := 'ccp_' || encode(extensions.gen_random_bytes(24), 'base64url');
  
  -- Hash the key for storage using pgcrypto
  hashed_key := crypt(new_key, gen_salt('bf', 8));

  -- Insert the hashed key into the table
  insert into public.api_keys (user_id, key_name, api_key_hash)
  values (p_user_id, p_key_name, hashed_key);

  -- Return the plaintext key to the user ONCE.
  return new_key;
end;
$$ language plpgsql security definer;

-- Function to delete an API key
create or replace function public.delete_api_key(p_key_id bigint, p_user_id uuid)
returns void as $$
begin
  delete from public.api_keys
  where id = p_key_id and user_id = p_user_id;
end;
$$ language plpgsql;

-- NEW function to verify an API key and get the user ID
create or replace function public.verify_api_key(p_api_key text)
returns uuid as $$
declare
  v_user_id uuid;
  v_key_id bigint;
begin
  select user_id, id into v_user_id, v_key_id from public.api_keys
  where api_key_hash = crypt(p_api_key, api_key_hash)
  limit 1;
  
  -- If a user was found, update the usage stats
  if v_user_id is not null then
    update public.api_keys
    set
      last_used_at = timezone('utc'::text, now()),
      request_count = request_count + 1
    where id = v_key_id;
  end if;
  
  return v_user_id;
end;
$$ language plpgsql security definer;


-- Grant execute permissions on the functions to authenticated users and anon for the verify function
grant execute on function public.create_api_key(uuid, text) to authenticated;
grant execute on function public.delete_api_key(bigint, uuid) to authenticated;
grant execute on function public.verify_api_key(text) to anon, authenticated;
